export type Language = "zh" | "en";

export const text = {
  zh: {
    loadingEditor: "正在加载本地编辑器...",
    preparingEditor: "正在准备本地编辑器...",
    localContext: "本地处理 · 单图编辑",
    title: "授权图片区域修复",
    private: "图片不上传",
    themeLight: "白天模式",
    themeDark: "夜晚模式",
    languageToggle: "Switch to English",
    consentTitle: "开始前请确认授权",
    consentBody:
      "仅处理您拥有版权或已取得明确修改授权的图片。禁止移除他人版权标识、平台保护标记、素材站预览标记，或利用本工具规避付费、许可和访问限制。系统无法通过技术手段判断真实版权归属。",
    consentCheck: "我确认符合上述授权要求",
    chooseImageLabel: "选择图片",
    uploadReady: "选择一张需要处理的图片",
    uploadLocked: "确认授权后选择图片",
    fileHelp: "JPEG、PNG 或 WebP，最大 10 MB、1200 万像素。图片仅保存在当前页面内存中。",
    checking: "正在检查...",
    takePhoto: "拍照",
    decodeFailed: "图片解码失败，文件可能已损坏。",
    openFailed: "无法打开图片。设备内存不足时，请选择尺寸更小的文件后重试。",
    terms: "服务条款",
    privacy: "隐私说明",
    complaints: "投诉与下架",
    editorLabel: "图片编辑器",
    maskTools: "遮罩工具",
    tools: {
      select: "选择",
      rectangle: "矩形选区",
      brush: "添加画笔",
      eraser: "橡皮擦",
      hand: "平移",
    },
    fit: "适应窗口",
    undo: "撤销",
    redo: "重做",
    deleteSelection: "删除选区",
    brush: "笔刷",
    brushSize: "笔刷大小",
    inspectorLabel: "图片和遮罩信息",
    currentImage: "当前图片",
    changeImage: "换一张",
    outputSize: "输出尺寸",
    originalSize: "原始尺寸",
    transparency: "透明度",
    alphaKept: "保留 Alpha",
    noAlpha: "无 Alpha",
    downsampled: "为控制内存，最终输出将使用上方工作尺寸。",
    autoCandidates: "自动候选",
    find: "查找",
    noCandidates: "未找到可靠候选，可继续手动编辑。",
    candidatesCount: (count: number) => `${count} 个文字状候选`,
    acceptAll: "全部接受",
    ignore: "忽略",
    candidate: (index: number) => `候选 ${index}`,
    acceptCandidate: (index: number) => `接受候选 ${index}`,
    deleteCandidate: (index: number) => `删除候选 ${index}`,
    candidateHint: "检测结果只作为候选，不代表版权归属结论。",
    repairArea: "修复区域",
    pixels: "像素",
    coverageLabel: (percent: string) => `遮罩覆盖率 ${percent}%`,
    warningArea: "区域超过 10%，传统修复可能产生明显纹理问题。",
    blockedArea: "区域超过 25%，请缩小选区后再处理。",
    confirmWarning: "选区覆盖率超过 10%，结果可能出现明显纹理问题。仍要继续吗？",
    status: {
      detecting: "正在查找候选",
      loading: "正在加载 OpenCV",
      initializing: "正在初始化",
      processing: "正在修复",
    },
    cancelTask: "取消任务",
    recoverWorker: "恢复 Worker",
    repair: "修复区域",
    clearMask: "清空遮罩",
    resultLabel: "修复结果",
    editAgain: "重新编辑",
    resultModeLabel: "结果显示方式",
    modes: {
      compare: "对比",
      result: "结果",
      original: "原图",
      mask: "遮罩",
    },
    compareBoundary: "原图与结果分界",
    downloadResult: "下载结果",
    format: "格式",
    quality: "质量",
    jpegAlphaWarning: "JPEG 不支持透明度，导出时透明区域将明确展平为白色。选择 PNG 或 WebP 可保留 Alpha。",
    download: "下载",
    canvasUnavailable: "浏览器无法创建导出画布。",
    unsupportedEncoding: "当前浏览器不支持所选编码格式。",
    downloadStarted: "下载已开始。",
    repairedSuffix: "修复结果",
    validation: {
      empty: "文件为空。",
      "too-large": "文件超过 10 MB 上限。",
      "unsupported-extension": "仅支持 JPEG、PNG 和 WebP 文件。",
      "unsupported-mime": "浏览器报告的文件类型不受支持。",
      "invalid-signature": "文件扩展名、类型和实际内容不一致。",
      animated: "不支持动画图片。",
      "invalid-dimensions": "图片尺寸无效。",
      "too-many-pixels": "图片超过 1200 万像素上限。",
    },
  },
  en: {
    loadingEditor: "Loading local editor...",
    preparingEditor: "Preparing local editor...",
    localContext: "Local processing · Single image",
    title: "Authorized Image Area Repair",
    private: "Images never upload",
    themeLight: "Light mode",
    themeDark: "Dark mode",
    languageToggle: "切换到中文",
    consentTitle: "Confirm authorization first",
    consentBody:
      "Only process images you own or have explicit permission to modify. Do not remove copyright marks, platform protection marks, stock preview marks, or use this tool to bypass payment, licenses, or access limits. The system cannot determine actual rights ownership.",
    consentCheck: "I confirm this image meets the authorization requirements",
    chooseImageLabel: "Choose image",
    uploadReady: "Choose an image to process",
    uploadLocked: "Confirm authorization before choosing an image",
    fileHelp: "JPEG, PNG, or WebP, up to 10 MB and 12 million pixels. The image stays only in this page's memory.",
    checking: "Checking...",
    takePhoto: "Camera",
    decodeFailed: "Image decoding failed. The file may be damaged.",
    openFailed: "Unable to open the image. If device memory is low, choose a smaller file and try again.",
    terms: "Terms",
    privacy: "Privacy",
    complaints: "Complaints",
    editorLabel: "Image editor",
    maskTools: "Mask tools",
    tools: {
      select: "Select",
      rectangle: "Rectangle",
      brush: "Brush",
      eraser: "Eraser",
      hand: "Pan",
    },
    fit: "Fit to window",
    undo: "Undo",
    redo: "Redo",
    deleteSelection: "Delete selection",
    brush: "Brush",
    brushSize: "Brush size",
    inspectorLabel: "Image and mask information",
    currentImage: "Current image",
    changeImage: "Change",
    outputSize: "Output size",
    originalSize: "Original size",
    transparency: "Transparency",
    alphaKept: "Alpha kept",
    noAlpha: "No Alpha",
    downsampled: "To control memory use, the final output will use the working size above.",
    autoCandidates: "Auto candidates",
    find: "Find",
    noCandidates: "No reliable candidates found. You can keep editing manually.",
    candidatesCount: (count: number) => `${count} text-like candidate${count === 1 ? "" : "s"}`,
    acceptAll: "Accept all",
    ignore: "Ignore",
    candidate: (index: number) => `Candidate ${index}`,
    acceptCandidate: (index: number) => `Accept candidate ${index}`,
    deleteCandidate: (index: number) => `Delete candidate ${index}`,
    candidateHint: "Detection results are only candidates, not conclusions about rights ownership.",
    repairArea: "Repair area",
    pixels: "pixels",
    coverageLabel: (percent: string) => `Mask coverage ${percent}%`,
    warningArea: "Area exceeds 10%; traditional repair may create visible texture artifacts.",
    blockedArea: "Area exceeds 25%. Reduce the selection before processing.",
    confirmWarning: "Selection coverage exceeds 10%; the result may show visible texture artifacts. Continue?",
    status: {
      detecting: "Finding candidates",
      loading: "Loading OpenCV",
      initializing: "Initializing",
      processing: "Repairing",
    },
    cancelTask: "Cancel task",
    recoverWorker: "Recover Worker",
    repair: "Repair area",
    clearMask: "Clear mask",
    resultLabel: "Repair result",
    editAgain: "Edit again",
    resultModeLabel: "Result view mode",
    modes: {
      compare: "Compare",
      result: "Result",
      original: "Original",
      mask: "Mask",
    },
    compareBoundary: "Original and result split",
    downloadResult: "Download result",
    format: "Format",
    quality: "Quality",
    jpegAlphaWarning: "JPEG does not support transparency. Transparent areas will be flattened to white. Choose PNG or WebP to keep Alpha.",
    download: "Download",
    canvasUnavailable: "The browser cannot create an export canvas.",
    unsupportedEncoding: "The current browser does not support the selected encoding format.",
    downloadStarted: "Download started.",
    repairedSuffix: "repaired",
    validation: {
      empty: "The file is empty.",
      "too-large": "The file exceeds the 10 MB limit.",
      "unsupported-extension": "Only JPEG, PNG, and WebP files are supported.",
      "unsupported-mime": "The file type reported by the browser is not supported.",
      "invalid-signature": "The extension, MIME type, and file content do not match.",
      animated: "Animated images are not supported.",
      "invalid-dimensions": "The image dimensions are invalid.",
      "too-many-pixels": "The image exceeds the 12 million pixel limit.",
    },
  },
} as const;

export type UiText = (typeof text)[Language];
